WIP: new grey matter configuration style
greymatter-io/produce-aisle pull request #2
Opened 2022-05-11 19:46 UTC by alecholmez

2022-05-16 18:20 UTC, dontlaugh commented on scripts/build
> +esac
newline

2022-05-18 01:32 UTC, moosecanswim commented on README.md
> +* `services/inputs.cue`: a cue file in `package mesh` that contains defaults, overrides, and user inputted values.
Should this be `package services`?

2022-05-18 02:20 UTC, moosecanswim commented
Hey Alec, I think this is a great rework of the cue files.  

I made some inline comments for the readme but those wont affect the logic of this repo.
- I think we should link add a link to the readme to our docs site where we explain how to apply the mesh configs. 
- Additionally i think we should add a tutorial about how to create your own mesh configs. ex:

```markdown
### How to create your own mesh configs
When you want to create your own mesh configs create a new folder in services.
Inside that directory create a file `myservice.cue` and add `package services` as the first line.
...
```
- Could you add something to the readme about what `apple/apple.cue` and`applications/*.cue`.  Why are there two cue files in applications directory and why there is only one in apple.  Stating that there is one file per data plane connection could be useful.

Question, how do we expect users to use this, from a greymatter admin perspective, as well as a tenant team?
From what i see so far is a team that owns the mesh would copy this repo and make modifications to the `inputs.cue` and `intermediate.cue`.  For mesh's that have a monorepo of mesh configs this would not be a concern but when individual teams own their mesh config repo the admin team would need to pass those files to every tenant team that will create their own mesh configs.

2022-05-18 02:21 UTC, moosecanswim requested changes

2022-05-18 20:44 UTC, alecholmez commented on README.md
> +* `EXPORT.cue`: the end all final conglomerate of your mesh configurations in their respective groupings. These is what is meant
Ah so the evaluated part is very CUE specific. CUE refers to unifying values as `evaluating` so when we use the CUE CLI like `cue eval -e all_configs` we are saying evaluate the result of `all_configs`. I think yea I can massage that wording to make that a bit more understandable.

2022-05-18 20:46 UTC, alecholmez commented on EXPORT.cue
> +package produce
Okay cool, I will add some comments around this. My idea behind this package name was it was a mesh name. So for example the repo might hold SEED mesh configs, so we can call the final package `seed`.

2022-05-19 13:58 UTC, moosecanswim commented on README.md
> +* `EXPORT.cue`: the end all final conglomerate of your mesh configurations in their respective groupings. These is what is meant
Thanks for the clarification.

2022-05-19 13:59 UTC, moosecanswim commented on EXPORT.cue
> +package produce
Ahhh icic.  By change `seed` somewhat works with `produce`

2022-05-20 16:30 UTC, alecholmez commented
Kyle's questions were answered internally at this meeting: [notes](https://docs.google.com/document/d/1IDlKSkWc5PfTA80_tgU2XGUM8RdMtUYo8tdupKDC33w/edit#heading=h.29o1v4eet16n)

2022-05-20 16:32 UTC, merged